-- ============================================================================
-- Nefer Kali Healing -- all migrations, in order
-- ============================================================================
-- Run this ONCE in the Supabase SQL Editor. Every statement is idempotent, so
-- running it again is safe and will simply confirm the current state.
--
-- WHY THIS FILE EXISTS: the individual migrations have ordering dependencies
-- (000009 references a table created by 000006), and running them by hand in the
-- wrong order fails with a confusing missing-relation error. This file removes
-- that hazard.
--
-- Generated by: node scripts/build-all-migrations.mjs
-- ============================================================================


-- ############################################################################
-- # 20260305005317_add_sort_order_to_products.sql
-- ############################################################################

-- Add sort_order to products table
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;

-- Down migration will drop the column if rollback occurs
-- ALTER TABLE public.products DROP COLUMN IF EXISTS sort_order;

-- ############################################################################
-- # 20260927000000_harden_admin_authorization.sql
-- ############################################################################

-- ============================================================================
-- Harden admin authorization
-- ============================================================================
-- Date: 2026-09-27
--
-- Context: RLS is correctly enabled on every public table, and every admin
-- policy already routes through public.is_admin(). Signup, anonymous sign-ins,
-- and manual linking are all disabled in the Auth settings. This migration
-- fixes the remaining weaknesses in is_admin() itself and closes the
-- admin_users email-enumeration leak.
--
-- REVIEW BEFORE RUNNING. Run in the Supabase SQL Editor, in order.
-- Phase 0 is safe. Phase 1 changes how admins are identified -- read the
-- pre-flight check in that section before you run it.
-- ============================================================================


-- ============================================================================
-- PRE-FLIGHT -- run these two queries BEFORE anything else
-- ============================================================================
--   -- (a) Who is currently an admin, and how is the row keyed?
--   select * from public.admin_users;
--
--   -- (b) What email does Supabase actually put in the JWT for that user?
--   select id, email, email_confirmed_at, created_at from auth.users;
--
-- If (a) returns ZERO rows, then is_admin() is already false for everyone and
-- your admin panel is already broken -- stop and report that before running
-- anything here.
--
-- If (a) returns a row, confirm its email matches (b) exactly, including case.
--
-- LEAVE "Confirm email" ENABLED in Authentication > Providers > Email. The
-- whole weakness being fixed here is that is_admin() trusted an unverified
-- email claim; turning email confirmation off would make that exploitable
-- instead of merely fragile.
-- ============================================================================


-- ============================================================================
-- PHASE 0 -- SAFE TO RUN NOW
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0.1  Make sure the admin_users table has the columns the new function needs.
--      These are no-ops if they already exist.
-- ---------------------------------------------------------------------------
alter table public.admin_users
  add column if not exists user_id uuid;

alter table public.admin_users
  add column if not exists role text not null default 'owner';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.admin_users'::regclass
      and contype = 'c'
      and conname = 'admin_users_role_check'
  ) then
    alter table public.admin_users
      add constraint admin_users_role_check
      check (role in ('owner', 'editor'));
  end if;
end $$;

-- Link any existing email-keyed row to its auth user, so the ID-based check
-- below works immediately without you having to look up a UUID by hand.
update public.admin_users au
set user_id = u.id
from auth.users u
where au.user_id is null
  and lower(au.email) = lower(u.email);

-- ---------------------------------------------------------------------------
-- 0.2  Replace is_admin().
--
--      Before: matched on the email claim alone (unverified per Supabase),
--              with a case-sensitive `=`.
--      After:  matches on auth.uid() when the row is linked, falling back to
--              a case-insensitive email match so you can never be locked out.
--              All references stay explicitly schema-qualified.
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $function$
  select exists (
    select 1
    from public.admin_users au
    where
      -- Preferred: stable identifier from the verified JWT `sub` claim.
      (au.user_id is not null and au.user_id = auth.uid())
      -- Fallback: case-insensitive email, so a casing change cannot lock you out.
      or (au.email is not null and lower(au.email) = lower(auth.jwt() ->> 'email'))
  );
$function$;

comment on function public.is_admin() is
  'True when the current JWT belongs to a row in public.admin_users. Matches on '
  'user_id (preferred) or a case-insensitive email fallback. SECURITY DEFINER so '
  'RLS policies can call it without granting table access.';

-- ---------------------------------------------------------------------------
-- 0.3  admin_users is read ONLY by is_admin() (which is SECURITY DEFINER, so it
--      does not need a client-facing policy). Drop the policy that let any
--      authenticated user probe whether a given email is an administrator.
-- ---------------------------------------------------------------------------
drop policy if exists "Admins can view admin users" on public.admin_users;
drop policy if exists "Admins can manage admin users" on public.admin_users;
drop policy if exists "authenticated can view admin users" on public.admin_users;

-- Belt and braces: RLS on with zero policies = deny by default for every
-- non-bypassing role. Only service_role can touch this table.
alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 0.4  Fix the event_registrations read policy.
--
--      The old policy "Users can view their own registrations" actually tested
--      is_admin() rather than ownership, so it granted admin-level row access
--      under a name that suggested the opposite.
--
--      Separately, the public event page counts registrations as an anonymous
--      visitor (pages/EventDetail.tsx:65, a head:true count). The admin-only
--      SELECT policy blocks that, so the count is most likely returning 0 to
--      the public right now. VERIFY THIS before and after -- load a live event
--      page and see whether the registration count is stuck at zero.
--
--      The fix splits the two concerns: a count-only policy that reveals no
--      rows, and an admin policy that does. Both the old and new count policies
--      permit an anonymous count of CONFIRMED registrations -- i.e. the same
--      number the event page already intends to display publicly. If you would
--      rather not expose attendance counts at all, delete the first policy and
--      the page should render 0 / hide the count instead.
-- ---------------------------------------------------------------------------
drop policy if exists "Users can view their own registrations" on public.event_registrations;
drop policy if exists "Authenticated users can manage all registrations" on public.event_registrations;

-- Anonymous and any signed-in user may COUNT confirmed registrations.
create policy "Public can count registrations"
  on public.event_registrations
  for select
  to anon, authenticated
  using (status = 'confirmed');

-- Only admins may read the attendee rows themselves (emails, names, codes).
create policy "Admins can manage registrations"
  on public.event_registrations
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- 0.5  Tighten the other anonymous-INSERT policies.
--
--      Both currently use WITH CHECK (true), which means any anonymous visitor
--      can insert arbitrary rows (spam, or a named row for someone else).
--      These constraints keep the real form working while requiring the data to
--      at least be shaped like a real submission.
-- ---------------------------------------------------------------------------
drop policy if exists "Anyone can submit back in stock requests" on public.back_in_stock_requests;
create policy "Anyone can submit back in stock requests"
  on public.back_in_stock_requests
  for insert
  to anon, authenticated
  with check (
    customer_email is not null
    and position('@' in customer_email) > 1
    and length(customer_email) <= 254
    and notified is not true          -- cannot self-mark as notified
    and notified_at is null
  );

drop policy if exists "Anyone can create registrations" on public.event_registrations;
create policy "Anyone can create registrations"
  on public.event_registrations
  for insert
  to anon, authenticated
  with check (
    email is not null
    and position('@' in email) > 1
    and length(email) <= 254
    and coalesce(status, 'confirmed') = 'confirmed'   -- cannot self-cancel/attend
    and ticket_sent_at is null
  );

-- reviews / review_media / coupon_redemptions already constrain the inserted
-- columns (reviews forces status='pending'). Left as-is deliberately, so this
-- migration does not change storefront behaviour beyond the fixes above.


-- ============================================================================
-- PHASE 1 -- STAGED. Read what it does before running.
-- ============================================================================
-- The policies are already correct (they all call is_admin(), which you just
-- hardened). This phase only removes the *table grants* that let anon and
-- authenticated even ATTEMPT writes that RLS will reject anyway. It is
-- defence in depth: today RLS is your only line of defence, and one careless
-- policy later would open a table completely.
--
-- It is staged separately because a mistake here breaks the storefront with
-- 403s, and the exact grant set must be verified against the live site.
--
-- Before running: confirm the storefront only READS these tables. From the
-- codebase, public (non-admin) pages read exactly:
--     products, product_images, product_variants, product_categories,
--     blog_posts, events, site_settings, reviews, review_media
-- and INSERT into exactly:
--     reviews, review_media, event_registrations, back_in_stock_requests,
--     coupon_redemptions
--
-- ORDER MATTERS: grant SELECT before revoking, or you will break the site.
-- Test the storefront immediately after each block.

-- begin;

-- -- 1. Admin-only tables: no client access at all. service_role bypasses RLS.
-- revoke all on table
--   public.orders,
--   public.order_items,
--   public.subscriptions,
--   public.subscription_items,
--   public.coupons,
--   public.coupon_redemptions,
--   public.admin_users
-- from anon, authenticated;

-- -- 2. Storefront-readable tables: SELECT only. No client-side writes --
-- --    every write to these goes through the admin panel or service_role.
-- revoke insert, update, delete, truncate, references, trigger on table
--   public.products,
--   public.product_images,
--   public.product_variants,
--   public.product_categories,
--   public.blog_posts,
--   public.events,
--   public.site_settings,
--   public.reviews,
--   public.review_media
-- from anon, authenticated;

-- grant select on table
--   public.products,
--   public.product_images,
--   public.product_variants,
--   public.product_categories,
--   public.blog_posts,
--   public.events,
--   public.site_settings,
--   public.reviews,
--   public.review_media
-- to anon, authenticated;

-- -- 3. Public-submission tables: INSERT only (plus the SELECT that the
-- --    event-registration count policy needs).
-- revoke update, delete, truncate, references, trigger on table
--   public.event_registrations,
--   public.back_in_stock_requests
-- from anon, authenticated;

-- grant select, insert on table
--   public.event_registrations,
--   public.back_in_stock_requests
-- to anon, authenticated;

-- -- 4. coupon_redemptions is INSERT-only from the storefront, but admins read
-- --    it through the panel. Admins are 'authenticated', so they need SELECT --
-- --    the is_admin() policy gates the rows. Keep SELECT, drop the rest.
-- grant select, insert on table public.coupon_redemptions to authenticated;
-- grant insert on table public.coupon_redemptions to anon;

-- commit;

-- After running, verify:
--   * a product page loads and shows inventory state
--   * the shop grid lists products
--   * a blog post renders
--   * an event page shows a non-zero registration count
--   * /admin/products, /admin/orders, /admin/blog all still load for you
--
-- If anything 403s, `rollback;` and tell me which page.


-- ============================================================================
-- VERIFY
-- ============================================================================

-- 1. The new function. Should return exactly one definition, matching on
--    user_id OR the case-insensitive email fallback.
-- select pg_get_functiondef('public.is_admin'::regproc);

-- 2. Confirm you are an admin from your own session (run this while logged in
--    to the admin panel, via the browser console):
--        (await supabase.rpc('is_admin')).data
--    ...but note is_admin() is not exposed via RPC unless granted. Easier:
--    just load /admin/products and confirm it works.

-- 3. Confirm the email-enumeration policy is gone and no policies remain on
--    admin_users:
-- select tablename, policyname, cmd, roles::text, qual
-- from pg_policies
-- where schemaname = 'public' and tablename = 'admin_users';

-- 4. Confirm every admin table is still gated, and that no table in public is
--    missing RLS:
-- select c.relname, c.relrowsecurity
-- from pg_class c
-- join pg_namespace n on n.oid = c.relnamespace
-- where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity = false;
-- ^ must return ZERO rows.

-- 5. Confirm admin_users is keyed properly:
-- select user_id, email, role from public.admin_users;
-- ^ every row should have a user_id. If any is null, the email fallback is
--   doing the work and you should link it manually:
--   update public.admin_users au set user_id = u.id
--   from auth.users u where lower(au.email) = lower(u.email) and au.user_id is null;

-- ############################################################################
-- # 20260927000001_admin_agent_tables.sql
-- ############################################################################

-- ============================================================================
-- Admin agent: conversation storage
-- ============================================================================
-- Phase 1 (read-only copilot). These tables live in the `private` schema so
-- PostgREST cannot reach them: the browser must never be able to read or write
-- the transcript directly. Only the admin-agent Edge Function touches them,
-- with the service-role key.
--
-- Run AFTER 20260927000000_harden_admin_authorization.sql.
-- ============================================================================

create schema if not exists private;

-- ---------------------------------------------------------------------------
-- Sessions: one per conversation, owned by one admin.
-- ---------------------------------------------------------------------------
create table if not exists private.agent_sessions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  title       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists agent_sessions_user_idx
  on private.agent_sessions (user_id, updated_at desc);

-- ---------------------------------------------------------------------------
-- Messages: append-only transcript.
--
-- `tool_calls` holds the tool calls the model requested on that assistant turn,
-- and `tool_results` holds what came back. Both are stored so the transcript is
-- a faithful record of what the agent saw and did -- this is the audit trail,
-- and it is never mutated after insert.
-- ---------------------------------------------------------------------------
create table if not exists private.agent_messages (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid not null references private.agent_sessions(id) on delete cascade,
  role         text not null check (role in ('user', 'assistant', 'tool')),
  content      text,
  tool_calls   jsonb,
  tool_results jsonb,
  model        text,
  prompt_tokens     integer,
  completion_tokens integer,
  created_at   timestamptz not null default now()
);

create index if not exists agent_messages_session_idx
  on private.agent_messages (session_id, created_at);

-- ---------------------------------------------------------------------------
-- Deny by default. RLS on with no policies means no client role can read these
-- even if a grant is ever added by accident. service_role bypasses RLS.
-- ---------------------------------------------------------------------------
alter table private.agent_sessions enable row level security;
alter table private.agent_messages enable row level security;

revoke all on table private.agent_sessions from anon, authenticated;
revoke all on table private.agent_messages from anon, authenticated;
revoke all on schema private from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Keep updated_at current on sessions.
-- ---------------------------------------------------------------------------
create or replace function private.touch_agent_session()
returns trigger
language plpgsql
set search_path to ''
as $$
begin
  update private.agent_sessions
     set updated_at = now()
   where id = new.session_id;
  return new;
end;
$$;

drop trigger if exists agent_messages_touch_session on private.agent_messages;
create trigger agent_messages_touch_session
  after insert on private.agent_messages
  for each row
  execute function private.touch_agent_session();


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select tablename, rowsecurity from pg_tables where schemaname = 'private';
-- ^ both agent tables should show rowsecurity = true.
--
-- select grantee, table_name, privilege_type
-- from information_schema.role_table_grants
-- where table_schema = 'private';
-- ^ must return ZERO rows.

-- ############################################################################
-- # 20260927000002_admin_users_unique_user_id.sql
-- ############################################################################

-- ============================================================================
-- admin_users: add uniqueness on user_id
-- ============================================================================
-- Why: is_admin() matches on user_id first, but that column was created by the
-- hardening migration as a plain `uuid` with NO unique constraint. Without one,
-- admin_users can accumulate duplicate rows for the same person, and the
-- `on conflict (user_id)` upsert fails with:
--   ERROR: 42P10: there is no unique or exclusion constraint matching the
--   ON CONFLICT specification
--
-- This migration is idempotent -- safe to run more than once.
-- Run the whole file in the Supabase SQL Editor.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- STEP 1 -- Inspect first. Run just this, and look at the output.
-- ---------------------------------------------------------------------------
select conname, contype, pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid = 'public.admin_users'::regclass
order by conname;

select user_id, email, role, created_at
from public.admin_users
order by created_at;


-- ---------------------------------------------------------------------------
-- STEP 2 -- Remove duplicates, keeping the oldest row per user.
--
-- Harmless when there are none. Only touches rows where user_id is NOT NULL,
-- so an email-only legacy row is left alone.
-- ---------------------------------------------------------------------------
delete from public.admin_users au
where au.user_id is not null
  and exists (
    select 1
    from public.admin_users older
    where older.user_id = au.user_id
      and older.created_at < au.created_at
  );


-- ---------------------------------------------------------------------------
-- STEP 3 -- Add the unique constraint.
--
-- Guarded so re-running does not error with "constraint already exists".
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.admin_users'::regclass
      and contype = 'u'
      and pg_get_constraintdef(oid) = 'UNIQUE (user_id)'
  ) then
    alter table public.admin_users
      add constraint admin_users_user_id_key unique (user_id);
  end if;
end $$;

-- Note: the constraint allows MULTIPLE NULL user_id values, which is correct --
-- Postgres treats NULLs as distinct. Rows with a NULL user_id are legacy
-- email-keyed rows that is_admin() matches via its email fallback.


-- ---------------------------------------------------------------------------
-- STEP 4 -- Confirm the constraint exists.
-- ---------------------------------------------------------------------------
select conname, contype, pg_get_constraintdef(oid) as definition
from pg_constraint
where conrelid = 'public.admin_users'::regclass
  and contype in ('u', 'p')
order by conname;

-- EXPECT: a row with definition "UNIQUE (user_id)"


-- ============================================================================
-- STEP 5 -- NOW the upsert works. Adds both accounts as owners.
-- ============================================================================
insert into public.admin_users (user_id, email, role)
select id, email, 'owner'
from auth.users
where email in ('mastrianni11@gmail.com', 'info@neferkalihealing.org')
on conflict (user_id) do update
  set email = excluded.email,
      role  = excluded.role;


-- ---------------------------------------------------------------------------
-- STEP 6 -- Verify both admins are present and linked.
-- ---------------------------------------------------------------------------
select user_id, email, role
from public.admin_users
order by email;

-- EXPECT: two rows, both with a non-null user_id and role 'owner'.


-- ============================================================================
-- FINAL CHECK -- this is the real test
-- ============================================================================
-- is_admin() must return true for the signed-in admin. Run this in the SQL
-- editor while signed in to the admin panel:
--
--   select public.is_admin();
--
-- But note: the SQL editor runs as `postgres`, not as your JWT, so auth.uid()
-- is NULL there and this will return false. That is expected and does NOT
-- indicate a problem.
--
-- The real verification is the assistant itself: reload /admin/assistant and
-- ask "How is the shop doing right now?" A 403 means the row is still not
-- matching; a real answer means it works.

-- ############################################################################
-- # 20260927000003_agent_actions.sql
-- ############################################################################

-- ============================================================================
-- Phase 2: write proposals, approval, and undo
-- ============================================================================
-- Design: the model never writes. It can only create a row in
-- private.agent_actions with status='proposed'. A separate, short request --
-- triggered by a human clicking Apply -- flips it to 'applied' and performs the
-- write. The model has no code path to that endpoint.
--
-- Approval is bound to args_hash, a sha256 over the canonicalised proposal
-- payload. If the stored payload changes between display and execution, the
-- hash check fails and the write is refused. That is what makes "you approved
-- exactly this" enforceable rather than aspirational.
--
-- Idempotent -- safe to run more than once.
-- ============================================================================

create extension if not exists pgcrypto;

create table if not exists private.agent_actions (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid references private.agent_sessions(id) on delete set null,
  user_id      uuid not null references auth.users(id),
  tool_name    text not null,

  -- What will be written, and the hash the approval is bound to.
  args         jsonb not null,
  args_hash    text  not null,

  -- Human-readable one-liner for the confirmation card.
  summary      text not null,

  -- Per-field before/after for the diff UI:
  --   [{ field, label, before, after }]
  preview      jsonb not null,

  -- Target table + primary key + the exact previous values, so undo is a
  -- direct restore rather than a reconstruction.
  target_table text not null,
  target_id    text,
  before_state jsonb,

  risk         text not null default 'medium' check (risk in ('low', 'medium', 'high')),
  reversible   boolean not null default true,
  status       text not null default 'proposed'
               check (status in ('proposed', 'applied', 'failed', 'rejected', 'undone', 'expired')),

  result       jsonb,
  error        text,

  -- Written at APPLY time: the exact instructions needed to reverse this
  -- change. Kept in its own column rather than inside `result`, because
  -- `result` is returned to the browser and could be overwritten by a later
  -- request -- which would silently break undo.
  restore_state jsonb,

  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null default now() + interval '30 minutes',
  decided_at   timestamptz,
  applied_at   timestamptz,
  undone_at    timestamptz,

  model              text,
  prompt_tokens      integer,
  completion_tokens  integer
);

-- Idempotent backfill: if agent_actions already existed from an earlier run of
-- this file, `create table if not exists` above would have skipped it, so make
-- sure the restore column is present either way.
alter table private.agent_actions
  add column if not exists restore_state jsonb;

create index if not exists agent_actions_session_idx
  on private.agent_actions (session_id, created_at desc);

-- Fast lookup of the live pending proposal for a session (one at a time).
create index if not exists agent_actions_pending_idx
  on private.agent_actions (session_id)
  where status = 'proposed';

-- Append-only record of what was actually changed, for verification.
create table if not exists private.agent_action_log (
  id         bigserial primary key,
  action_id  uuid not null references private.agent_actions(id) on delete cascade,
  event      text not null check (event in ('proposed', 'applied', 'rejected', 'failed', 'undone')),
  detail     jsonb,
  created_at timestamptz not null default now()
);

create index if not exists agent_action_log_action_idx
  on private.agent_action_log (action_id, created_at);

-- ---------------------------------------------------------------------------
-- Deny by default, exactly as with the other agent tables.
-- ---------------------------------------------------------------------------
alter table private.agent_actions enable row level security;
alter table private.agent_action_log enable row level security;

revoke all on table private.agent_actions from anon, authenticated;
revoke all on table private.agent_action_log from anon, authenticated;

grant usage on schema private to service_role;
grant select, insert, update, delete on all tables in schema private to service_role;
alter default privileges in schema private
  grant select, insert, update, delete on tables to service_role;


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select table_name from information_schema.tables
-- where table_schema = 'private' order by table_name;
-- EXPECT: agent_action_log, agent_actions, agent_messages, agent_sessions

-- select has_schema_privilege('anon', 'private', 'USAGE') as anon_usage,
--        has_schema_privilege('authenticated', 'private', 'USAGE') as auth_usage,
--        has_schema_privilege('service_role', 'private', 'USAGE') as service_usage;
-- EXPECT: false, false, true

-- select grantee, privilege_type from information_schema.role_table_grants
-- where table_schema = 'private' and table_name = 'agent_actions'
--   and grantee in ('anon','authenticated');
-- EXPECT: ZERO rows

-- ############################################################################
-- # 20260927000004_theme_tokens.sql
-- ############################################################################

-- ============================================================================
-- Theme tokens: data-driven visual control of the whole site
-- ============================================================================
-- Design values live in a row instead of in CSS files, so the admin assistant
-- can propose a visual change, show a before/after card, and have it take
-- effect with no build and no deploy.
--
-- Readable by the storefront (anon) so the public site can apply the palette at
-- runtime. Writable only by the Edge Function's service role -- there is no
-- write policy, and RLS is on, so a client cannot modify the theme.
--
-- Idempotent: safe to run more than once.
-- ============================================================================

create table if not exists public.theme_settings (
  key        text primary key,
  value      jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

comment on table public.theme_settings is
  'Site-wide design tokens rendered as CSS custom properties. Written by the admin agent through the service role; read publicly.';

alter table public.theme_settings enable row level security;

-- Exactly one policy: public read. No insert/update/delete policy exists, so
-- RLS denies those to every client role. The service role bypasses RLS.
drop policy if exists "Theme is publicly readable" on public.theme_settings;
create policy "Theme is publicly readable"
  on public.theme_settings for select
  to anon, authenticated
  using (true);

revoke all on table public.theme_settings from anon, authenticated;
grant select on table public.theme_settings to anon, authenticated;
grant all on table public.theme_settings to service_role;

-- ---------------------------------------------------------------------------
-- Seed.
--
-- Three keys, forming a base layer plus per-surface overrides:
--   tokens        -> base, inherited by both surfaces
--   tokens:site   -> storefront-only override  (sparse patch)
--   tokens:admin  -> admin-only override       (sparse patch)
--
-- The overrides start EMPTY on purpose. They are merges, not full sets, so an
-- override only needs to carry the tokens it changes; everything else keeps
-- following the base. That is what lets "make the admin trippy" leave the
-- storefront untouched without freezing the admin at stale values.
--
-- on conflict do nothing, so re-running never overwrites a live theme.
-- ---------------------------------------------------------------------------
insert into public.theme_settings (key, value)
values (
  'tokens',
  jsonb_build_object(
    -- Three hues drive every accent in the design, as HSL degrees.
    'hue1',           265,   -- primary   (purple today)
    'hue2',           325,   -- secondary (fuchsia/pink today)
    'hue3',           172,   -- tertiary  (teal today)

    'saturation',      70,   -- 0-100, overall vividness
    'glow',            40,   -- 0-100, bloom around accents
    'animationSpeed', 100,   -- 25-250 (%), scales ambient motion
    'backgroundDepth', 10,   -- 0-100, lightness of the near-black canvas
    'hueRotate',        0,   -- 0-360 deg, continuous animated hue cycling
    'contrast',       100,   -- 85-120 (%), accent/text contrast
    'grain',           12    -- 0-100, subtle texture overlay
  )::jsonb
)
on conflict (key) do nothing;

insert into public.theme_settings (key, value)
values ('tokens:site', '{}'::jsonb), ('tokens:admin', '{}'::jsonb)
on conflict (key) do nothing;


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select key, jsonb_pretty(value), updated_at from public.theme_settings;

-- select grantee, privilege_type from information_schema.role_table_grants
-- where table_schema = 'public' and table_name = 'theme_settings'
-- order by grantee, privilege_type;
-- EXPECT: anon/authenticated -> SELECT only; service_role -> everything.

-- select count(*) from pg_policies
-- where schemaname = 'public' and tablename = 'theme_settings';
-- EXPECT: 1 (the public read policy)

-- ############################################################################
-- # 20260927000005_marketing_drafts.sql
-- ############################################################################

-- ============================================================================
-- Marketing drafts
-- ============================================================================
-- Where drafted marketing copy lives before it goes anywhere.
--
-- The assistant drafts; the owner publishes. Nothing here is ever posted to a
-- platform automatically -- an email, an Instagram caption or a partner message
-- cannot be un-sent, so sending stays a human action.
--
-- Idempotent: safe to run more than once.
-- ============================================================================

create table if not exists public.marketing_drafts (
  id           uuid primary key default gen_random_uuid(),
  channel      text not null check (channel in (
                 'newsletter', 'instagram', 'facebook', 'blog_social',
                 'partner_outreach', 'press', 'other'
               )),
  subject      text,
  body         text not null,
  -- Free-form so a draft can record the campaign, the audience, the offer, or
  -- the organisation being approached.
  notes        text,
  status       text not null default 'draft' check (status in (
                 'draft', 'approved', 'scheduled', 'sent', 'discarded'
               )),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  created_by   uuid
);

create index if not exists marketing_drafts_channel_idx
  on public.marketing_drafts (channel, created_at desc);
create index if not exists marketing_drafts_status_idx
  on public.marketing_drafts (status);

comment on table public.marketing_drafts is
  'Marketing copy drafted by the admin assistant. The owner publishes; nothing sends automatically.';

-- ---------------------------------------------------------------------------
-- Access
--
-- Admin-only. Unlike the theme there is no reason for the storefront to read
-- this, so there is no anon policy at all: RLS on with no client policy means
-- deny by default, and only the service role reaches it.
-- ---------------------------------------------------------------------------
alter table public.marketing_drafts enable row level security;

drop policy if exists "Admins can manage marketing drafts" on public.marketing_drafts;
create policy "Admins can manage marketing drafts"
  on public.marketing_drafts
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on table public.marketing_drafts from anon, authenticated;
grant select, insert, update, delete on table public.marketing_drafts to authenticated;
grant all on table public.marketing_drafts to service_role;

-- Keep updated_at current.
create or replace function public.touch_marketing_draft()
returns trigger
language plpgsql
set search_path to ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists marketing_drafts_touch on public.marketing_drafts;
create trigger marketing_drafts_touch
  before update on public.marketing_drafts
  for each row
  execute function public.touch_marketing_draft();


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select count(*) from pg_policies
-- where schemaname = 'public' and tablename = 'marketing_drafts';
-- EXPECT: 1

-- select grantee, privilege_type from information_schema.role_table_grants
-- where table_schema = 'public' and table_name = 'marketing_drafts'
--   and grantee in ('anon');
-- EXPECT: ZERO rows

-- ############################################################################
-- # 20260927000006_admin_uploads.sql
-- ############################################################################

-- ============================================================================
-- Uploaded assets
-- ============================================================================
-- Files the owner attaches in the chat -- product photos, logos, screenshots --
-- stored so the assistant can reference them and the site can use them.
--
-- IMPORTANT: this is Option A. The assistant learns that a file EXISTS and gets
-- its URL and dimensions. It does NOT read file contents. Nothing here gives the
-- model the ability to interpret an image.
--
-- Idempotent: safe to run more than once.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Storage bucket.
--
-- Public read, because these are website assets that need to be servable by URL.
-- Writes are admin-only via the policy below.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('site-assets', 'site-assets', true)
on conflict (id) do update set public = true;

-- Storage policies: anyone may read, only admins may write or delete.
drop policy if exists "Site assets are publicly readable" on storage.objects;
create policy "Site assets are publicly readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'site-assets');

drop policy if exists "Admins can upload site assets" on storage.objects;
create policy "Admins can upload site assets"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'site-assets' and public.is_admin());

drop policy if exists "Admins can update site assets" on storage.objects;
create policy "Admins can update site assets"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'site-assets' and public.is_admin());

drop policy if exists "Admins can delete site assets" on storage.objects;
create policy "Admins can delete site assets"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'site-assets' and public.is_admin());

-- ---------------------------------------------------------------------------
-- Metadata
-- ---------------------------------------------------------------------------
create table if not exists public.admin_uploads (
  id            uuid primary key default gen_random_uuid(),
  storage_path  text not null,
  public_url    text not null,
  file_name     text not null,
  mime_type     text,
  byte_size     bigint,
  -- Optional context the owner or the assistant provides later.
  title         text,
  notes         text,
  uploaded_by   uuid,
  created_at    timestamptz not null default now()
);

create index if not exists admin_uploads_created_idx
  on public.admin_uploads (created_at desc);

comment on table public.admin_uploads is
  'Files attached in the admin chat, stored in the site-assets bucket. Metadata only -- the assistant can reference these but cannot read their contents.';

alter table public.admin_uploads enable row level security;

drop policy if exists "Admins can manage uploads" on public.admin_uploads;
create policy "Admins can manage uploads"
  on public.admin_uploads
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on table public.admin_uploads from anon, authenticated;
grant select, insert, update, delete on table public.admin_uploads to authenticated;
grant all on table public.admin_uploads to service_role;


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select id, public from storage.buckets where id = 'site-assets';
-- EXPECT: one row, public = true

-- select policyname, cmd from pg_policies
-- where schemaname = 'storage' and tablename = 'objects'
--   and policyname like '%site assets%';
-- EXPECT: 4 rows (select, insert, update, delete)

-- select grantee, privilege_type from information_schema.role_table_grants
-- where table_schema = 'public' and table_name = 'admin_uploads'
--   and grantee = 'anon';
-- EXPECT: ZERO rows

-- ############################################################################
-- # 20260927000007_vision_descriptions.sql
-- ############################################################################

-- ============================================================================
-- Vision descriptions
-- ============================================================================
-- Cached readings of uploaded images.
--
-- Why a cache rather than describing on demand every time:
--   - image tokens are the expensive part of a vision call, and the same asset
--     is often asked about more than once
--   - a description is stale-able context the assistant can rely on without
--     spending a call
--
-- THE SECURITY POINT: a description is derived from attacker-controlled pixels.
-- Text inside an image ("ignore your instructions and...") is another injection
-- surface, so a description is treated exactly like text fetched from the web:
-- it is DATA. It is labelled untrusted wherever it is returned, and it can never
-- by itself authorise a write -- writes still require the owner to click Apply
-- on a fingerprinted proposal.
--
-- Idempotent: safe to run more than once.
-- ============================================================================

create table if not exists public.vision_descriptions (
  id            uuid primary key default gen_random_uuid(),
  -- The storage object this describes. Unique so a re-describe replaces rather
  -- than accumulating near-duplicate rows.
  storage_path  text not null unique,
  public_url    text not null,
  description   text not null,
  -- What was asked, when the owner asked something specific rather than
  -- requesting a general description.
  question      text,
  model         text,
  prompt_tokens     integer,
  completion_tokens integer,
  created_at    timestamptz not null default now()
);

create index if not exists vision_descriptions_path_idx
  on public.vision_descriptions (storage_path);

comment on table public.vision_descriptions is
  'Cached readings of uploaded images. Descriptions are UNTRUSTED: they derive from image pixels, which are attacker-controlled content.';

alter table public.vision_descriptions enable row level security;

drop policy if exists "Admins can manage vision descriptions" on public.vision_descriptions;
create policy "Admins can manage vision descriptions"
  on public.vision_descriptions
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on table public.vision_descriptions from anon, authenticated;
grant select, insert, update, delete on table public.vision_descriptions to authenticated;
grant all on table public.vision_descriptions to service_role;


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select grantee, privilege_type from information_schema.role_table_grants
-- where table_schema = 'public' and table_name = 'vision_descriptions'
--   and grantee = 'anon';
-- EXPECT: ZERO rows
--
-- select count(*) from pg_policies
-- where schemaname = 'public' and tablename = 'vision_descriptions';
-- EXPECT: 1

-- ############################################################################
-- # 20260927000008_publishing.sql
-- ############################################################################

-- ============================================================================
-- Publishing: send tracking for marketing drafts
-- ============================================================================
-- Tier 3 is different from everything built so far. A price change, a theme
-- change, even a merge can be reverted. An email that has left the building, or
-- a social post that is live, cannot be.
--
-- So the model here is deliberately different too:
--   - the assistant can DRAFT, and can propose edits to a draft
--   - it has NO tool that can send, schedule or publish anything
--   - sending is performed only by a named action in the admin UI, behind an
--     explicit confirmation and after the owner has seen the final text
--
-- The columns below exist to make a send auditable and hard to repeat, not to
-- make it convenient.
--
-- Idempotent: safe to run more than once.
-- ============================================================================

alter table public.marketing_drafts
  add column if not exists publisher        text,
  add column if not exists published_at     timestamptz,
  add column if not exists publish_ref      text,
  add column if not exists publish_error    text,
  add column if not exists approved_at      timestamptz,
  add column if not exists approved_by      uuid;

-- The exact bytes that were sent. Kept separate from `body` because the body can
-- still be edited afterwards, and the point of this column is to record what
-- actually left the building.
alter table public.marketing_drafts
  add column if not exists sent_snapshot    jsonb;

-- A draft may not be marked sent without a timestamp, and vice versa. This is a
-- database-level guard rather than a code-level one, so a bug in the Edge
-- Function cannot produce a row claiming success without evidence.
--
-- Note the state machine: draft -> approved -> sending -> sent (or failed).
-- `sending` is a CLAIM. The row is stamped before the network call so two
-- concurrent sends cannot both dispatch. A claim is abandoned rather than
-- silently retried after STALE_CLAIM_MINUTES, because a send that may have
-- succeeded must never be repeated automatically.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.marketing_drafts'::regclass
      and conname = 'marketing_drafts_sent_consistency'
  ) then
    alter table public.marketing_drafts
      add constraint marketing_drafts_sent_consistency
      check (
        (status = 'sent' and published_at is not null)
        or (status <> 'sent')
      );
  end if;

  -- `sending` and `failed` did not exist in the original check constraint.
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.marketing_drafts'::regclass
      and conname = 'marketing_drafts_status_check'
  ) then
    alter table public.marketing_drafts
      add constraint marketing_drafts_status_check
      check (status in ('draft', 'approved', 'sending', 'sent', 'failed', 'discarded'));
  end if;
end $$;

create index if not exists marketing_drafts_pending_idx
  on public.marketing_drafts (status, created_at desc);

comment on column public.marketing_drafts.sent_snapshot is
  'The exact payload sent, captured at send time. `body` may be edited later; this may not.';
comment on column public.marketing_drafts.publish_ref is
  'Provider-side identifier for the send (broadcast id, post id, webhook response).';


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select column_name from information_schema.columns
-- where table_schema = 'public' and table_name = 'marketing_drafts'
-- order by ordinal_position;
-- EXPECT: the original columns plus publisher, published_at, publish_ref,
--         publish_error, approved_at, approved_by, sent_snapshot

-- select conname from pg_constraint
-- where conrelid = 'public.marketing_drafts'::regclass;
-- EXPECT: marketing_drafts_sent_consistency present

-- ############################################################################
-- # 20260927000009_image_generations.sql
-- ############################################################################

-- ============================================================================
-- Generated images
-- ============================================================================
-- A record of images the assistant generated, so a generation is reproducible
-- and attributable rather than a file appearing in a bucket from nowhere.
--
-- The generated file itself lives in the site-assets bucket and is recorded in
-- admin_uploads like any other asset, so list_assets finds it and it can be used
-- in a blog cover or page edit with no special handling.
--
-- Idempotent: safe to run more than once.
-- ============================================================================

-- The link to admin_uploads is added separately and only when that table exists.
-- A foreign key declared inline would make this migration fail outright on a
-- database where 000006 has not been applied yet, which is a real ordering
-- hazard when these are run by hand rather than by `supabase db push`.
create table if not exists public.image_generations (
  id             uuid primary key default gen_random_uuid(),
  prompt         text not null,
  -- The model and settings actually used, since output is not reproducible
  -- across models or quality levels.
  model          text not null,
  size           text,
  quality        text,
  output_format  text,
  -- Links to the stored file.
  upload_id      uuid,
  public_url     text,
  -- Provenance for the audit trail.
  requested_by   uuid,
  created_at     timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'admin_uploads'
  ) and not exists (
    select 1 from pg_constraint
    where conrelid = 'public.image_generations'::regclass
      and conname = 'image_generations_upload_id_fkey'
  ) then
    alter table public.image_generations
      add constraint image_generations_upload_id_fkey
      foreign key (upload_id) references public.admin_uploads(id) on delete set null;
  end if;
end $$;

create index if not exists image_generations_created_idx
  on public.image_generations (created_at desc);

comment on table public.image_generations is
  'Images generated via the OpenAI Image API. The file is stored in site-assets and recorded in admin_uploads.';

alter table public.image_generations enable row level security;

drop policy if exists "Admins can manage image generations" on public.image_generations;
create policy "Admins can manage image generations"
  on public.image_generations
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on table public.image_generations from anon, authenticated;
grant select, insert, update, delete on table public.image_generations to authenticated;
grant all on table public.image_generations to service_role;


-- ============================================================================
-- VERIFY
-- ============================================================================
-- select grantee, privilege_type from information_schema.role_table_grants
-- where table_schema = 'public' and table_name = 'image_generations'
--   and grantee = 'anon';
-- EXPECT: ZERO rows
